//! Admin session authentication: Argon2id passwords, session cookies, and
//! the middleware that gates `/admin/*` behind them.
//!
//! Deliberately a second, separate mechanism from `crate::snapshot::hash_key`
//! (SHA-256 over `api_keys`), not a generalisation of it. The two verbs being
//! secured are different in a way that changes which hash is correct:
//!
//! - An **API key** authenticates a *caller invoking a model*. It is
//!   generated by this process (`generate_key`, 32 bytes of OS randomness),
//!   so it is already maximally high-entropy — a fast hash (SHA-256) is
//!   correct because there is nothing an attacker with the hash could
//!   feasibly brute-force offline.
//! - A **password** authenticates a *human logging into the admin UI*. It is
//!   chosen by that human, so it is low-entropy by construction — the
//!   textbook case a slow, memory-hard KDF (Argon2id) exists for, to make
//!   offline brute-forcing a stolen `password_hash` expensive even against a
//!   weak password.
//!
//! A **session token** (the cookie value) sits with API keys, not passwords,
//! for the same entropy reason: it is generated here, not chosen by a human,
//! so `token_hash` in `migrations/0011_sessions.sql` is SHA-256 too.
use argon2::password_hash::{PasswordHash, PasswordHasher, PasswordVerifier, SaltString};
use argon2::Argon2;
use rand::RngCore;
use sha2::{Digest, Sha256};
use sqlx::PgPool;

/// The cookie name every login sets and every `/admin/*` request is checked
/// against.
pub const SESSION_COOKIE: &str = "fastllm_session";

/// How long a session is valid for after login. Short enough that a stolen
/// cookie has a bounded lifetime, long enough that an operator working
/// through the admin UI is not repeatedly kicked back to the login page.
pub const SESSION_TTL_HOURS: i64 = 12;

/// Hash a human-chosen password with Argon2id and OWASP's current default
/// parameters (`Argon2::default()`: 19 MiB memory, 2 iterations, 1-lane
/// parallelism), returning the full PHC string (`$argon2id$v=19$...`) that
/// `principals.password_hash` stores — self-describing, so a future
/// parameter change does not invalidate already-stored hashes.
pub fn hash_password(password: &str) -> anyhow::Result<String> {
    // Not `SaltString::generate`: that takes rand_core 0.6's `CryptoRngCore`,
    // a different major version of a different crate from this workspace's
    // own `rand` (0.9), and pulling it in as a real dependency just for this
    // one call is not worth it. 16 bytes of OS randomness from `rand`
    // (already a dependency for `control::api::generate_key`) encoded the
    // same way `generate` does internally is equivalent and adds nothing new
    // to the dependency tree.
    let mut salt_bytes = [0u8; 16];
    rand::rng().fill_bytes(&mut salt_bytes);
    let salt =
        SaltString::encode_b64(&salt_bytes).map_err(|e| anyhow::anyhow!("encoding salt: {e}"))?;
    let hash = Argon2::default()
        .hash_password(password.as_bytes(), &salt)
        .map_err(|e| anyhow::anyhow!("hashing password: {e}"))?;
    Ok(hash.to_string())
}

/// Verify a presented password against a stored PHC hash. `false` on any
/// mismatch *or* malformed stored hash — a corrupt `password_hash` must fail
/// closed, not panic or authenticate.
pub fn verify_password(password: &str, stored_hash: &str) -> bool {
    let Ok(parsed) = PasswordHash::new(stored_hash) else {
        return false;
    };
    Argon2::default()
        .verify_password(password.as_bytes(), &parsed)
        .is_ok()
}

/// 32 bytes of OS randomness, the same shape as `control::api::generate_key`
/// and for the same reason: this is what makes hashing it with SHA-256
/// (rather than Argon2id) the right call — see the module doc comment.
fn generate_session_token() -> String {
    let mut bytes = [0u8; 32];
    rand::rng().fill_bytes(&mut bytes);
    format!("sess-{}", hex::encode(bytes))
}

fn hash_session_token(token: &str) -> [u8; 32] {
    Sha256::digest(token.as_bytes()).into()
}

/// Create a session row for `principal_id` and return the plaintext token to
/// set as the cookie value. Like `create_key`, the plaintext is returned
/// exactly once and never stored — only its hash is.
pub async fn create_session(pool: &PgPool, principal_id: i64) -> Result<String, sqlx::Error> {
    let token = generate_session_token();
    let expires_at = chrono::Utc::now() + chrono::Duration::hours(SESSION_TTL_HOURS);
    sqlx::query("INSERT INTO sessions (token_hash, principal_id, expires_at) VALUES ($1, $2, $3)")
        .bind(hash_session_token(&token).to_vec())
        .bind(principal_id)
        .bind(expires_at)
        .execute(pool)
        .await?;
    Ok(token)
}

/// Resolve a presented cookie value to the principal it belongs to, or
/// `None` if it does not exist, has expired, or names a disabled principal.
/// Never a database error the caller has to plumb through — a lookup that
/// cannot resolve a session is the same "not authenticated" outcome
/// regardless of why.
pub async fn authenticate_session(pool: &PgPool, token: &str) -> Option<i64> {
    let row: Option<(i64,)> = sqlx::query_as(
        "SELECT s.principal_id FROM sessions s
         JOIN principals p ON p.id = s.principal_id
         WHERE s.token_hash = $1 AND s.expires_at > now() AND NOT p.disabled",
    )
    .bind(hash_session_token(token).to_vec())
    .fetch_optional(pool)
    .await
    .ok()?;
    row.map(|(id,)| id)
}

/// Invalidate a session (logout). Deleting a row nobody presents again is a
/// no-op, not an error — logging out twice, or with a cookie already
/// expired, must not surface as a failure to the browser.
pub async fn delete_session(pool: &PgPool, token: &str) -> Result<(), sqlx::Error> {
    sqlx::query("DELETE FROM sessions WHERE token_hash = $1")
        .bind(hash_session_token(token).to_vec())
        .execute(pool)
        .await?;
    Ok(())
}

/// A syntactically valid Argon2id PHC string that verifies against nothing
/// real — never a login that legitimately succeeds against it. Only its
/// *shape* matters: `verify_login` runs `Argon2::verify_password` against
/// this whenever there is no real `password_hash` to check, purely so that
/// call happens (and costs the same handful of milliseconds Argon2id always
/// costs) on every rejection path, not only the "wrong password" one.
const DUMMY_LOGIN_HASH: &str =
    "$argon2id$v=19$m=19456,t=2,p=1$ADQjtj0AshO4tt+y8yYwgA$b9DCigRtGIAy9y9xRa9Lip7A9pBHRU+4AMK9lJkXDOA";

/// The pure decision `verify_login` reduces to once it has `row` in hand —
/// split out so it can be unit-tested without a database (see the tests
/// below) and so the timing-oracle fix has exactly one place to reason
/// about: every branch below runs `verify_password` exactly once, against
/// either the real hash or [`DUMMY_LOGIN_HASH`], before it is in a position
/// to decide anything. Skipping that call on a miss (the previous shape:
/// `let hash = hash?;` returning `None` before ever touching Argon2) is a
/// username-enumeration timing oracle — an unknown name or a `service_account`
/// (`password_hash IS NULL`) answers *fast* because no KDF ran, and a known,
/// enabled `user` answers *slow* because one did, regardless of whether the
/// password was right. Running the same KDF call on every path removes that
/// signal.
fn decide_login(row: Option<(i64, Option<String>, bool)>, password: &str) -> Option<i64> {
    // `None` (never a login that can succeed) whenever there is no real hash
    // to check: no such principal, or a principal that is disabled, or one
    // with no password set (`kind = 'service_account'`, or a `user` that
    // has never had `set_password` called for it).
    let real_hash = row
        .as_ref()
        .filter(|(_, _, disabled)| !disabled)
        .and_then(|(_, hash, _)| hash.as_deref());

    let password_matches = verify_password(password, real_hash.unwrap_or(DUMMY_LOGIN_HASH));

    match row {
        Some((id, _, _)) if real_hash.is_some() && password_matches => Some(id),
        _ => None,
    }
}

/// Look up a principal by name and verify a presented password against its
/// `password_hash`. `None` covers every rejection reason (no such
/// principal, wrong `kind`, no password set, disabled, wrong password)
/// without distinguishing which — the same "don't tell an attacker which
/// part was wrong" reasoning any login form follows, extended to *timing*
/// by [`decide_login`]: every one of those reasons costs the same one
/// Argon2id call, not zero for some and one for others.
pub async fn verify_login(pool: &PgPool, name: &str, password: &str) -> Option<i64> {
    let row: Option<(i64, Option<String>, bool)> = sqlx::query_as(
        "SELECT id, password_hash, disabled FROM principals WHERE name = $1 AND kind = 'user'",
    )
    .bind(name)
    .fetch_optional(pool)
    .await
    .ok()?;
    decide_login(row, password)
}

/// Set (or replace) a principal's password, promoting it to `kind = 'user'`
/// if it was not already — the same "this is now a login-capable identity"
/// step `fastllm-proxy set-password` and `PUT /admin/principals/{id}/password`
/// both need. Hashed with Argon2id, never encrypted: unlike
/// `model_backends.upstream_api_key` (which the proxy must present to a
/// backend and so must be recoverable), nothing ever needs the plaintext
/// password back.
pub async fn set_password(pool: &PgPool, principal_id: i64, password: &str) -> anyhow::Result<()> {
    let hash = hash_password(password)?;
    sqlx::query("UPDATE principals SET kind = 'user', password_hash = $1 WHERE id = $2")
        .bind(hash)
        .bind(principal_id)
        .execute(pool)
        .await?;
    Ok(())
}

/// Bootstraps (or resets) the very first admin login: finds or creates a
/// `kind = 'user'` principal named `name`, sets its password, and grants it
/// the `admin` role if it did not already have some role — `fastllm-proxy
/// set-password` is the only caller, and its whole reason to exist is that a
/// freshly migrated database otherwise has a `password_hash` column nobody
/// can ever fill in through the (session-gated) admin API itself.
pub async fn bootstrap_admin_user(
    pool: &PgPool,
    name: &str,
    password: &str,
) -> anyhow::Result<i64> {
    let mut tx = pool.begin().await?;
    let existing: Option<i64> = sqlx::query_scalar("SELECT id FROM principals WHERE name = $1")
        .bind(name)
        .fetch_optional(&mut *tx)
        .await?;
    let principal_id = match existing {
        Some(id) => id,
        None => {
            sqlx::query_scalar(
                "INSERT INTO principals (kind, name) VALUES ('user', $1) RETURNING id",
            )
            .bind(name)
            .fetch_one(&mut *tx)
            .await?
        }
    };
    let hash = hash_password(password)?;
    sqlx::query("UPDATE principals SET kind = 'user', password_hash = $1 WHERE id = $2")
        .bind(hash)
        .bind(principal_id)
        .execute(&mut *tx)
        .await?;
    // Whether this principal can actually administer, not merely whether it
    // holds *some* role. The original check was "has no role at all", which
    // silently skipped the grant for the seeded `bootstrap` principal — it
    // already holds `inference` so that keys minted against it can invoke
    // models. The documented first step (`set-password --name bootstrap`)
    // therefore produced an account that logged in successfully and then got
    // 403 from every admin route, including the ones needed to fix it.
    let can_administer: bool = sqlx::query_scalar(
        "SELECT EXISTS(
           SELECT 1 FROM principal_roles pr
           JOIN role_permissions rp ON rp.role_id = pr.role_id
           JOIN permissions p ON p.id = rp.permission_id
           WHERE pr.principal_id = $1 AND p.verb = 'config:write')",
    )
    .bind(principal_id)
    .fetch_one(&mut *tx)
    .await?;
    if !can_administer {
        sqlx::query(
            "INSERT INTO principal_roles (principal_id, role_id)
             SELECT $1, id FROM roles WHERE name = 'admin'
             ON CONFLICT DO NOTHING",
        )
        .bind(principal_id)
        .execute(&mut *tx)
        .await?;
    }
    tx.commit().await?;
    Ok(principal_id)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_password_round_trips_through_hash_and_verify() {
        let hash = hash_password("correct horse battery staple").unwrap();
        assert!(verify_password("correct horse battery staple", &hash));
    }

    #[test]
    fn the_wrong_password_is_rejected() {
        let hash = hash_password("correct horse battery staple").unwrap();
        assert!(!verify_password("wrong password", &hash));
    }

    #[test]
    fn a_malformed_stored_hash_fails_closed_rather_than_panicking() {
        assert!(!verify_password("anything", "not-a-phc-string"));
        assert!(!verify_password("anything", ""));
    }

    #[test]
    fn two_hashes_of_the_same_password_differ_by_salt() {
        // Argon2id salts randomly per call; two hashes of the same
        // plaintext must not be byte-identical, or a stolen `password_hash`
        // column would leak which users share a password.
        let a = hash_password("same-password").unwrap();
        let b = hash_password("same-password").unwrap();
        assert_ne!(a, b);
        assert!(verify_password("same-password", &a));
        assert!(verify_password("same-password", &b));
    }

    #[test]
    fn decide_login_accepts_only_a_matching_password_against_an_enabled_hashed_principal() {
        let hash = hash_password("right password").unwrap();
        assert_eq!(
            decide_login(Some((7, Some(hash.clone()), false)), "right password"),
            Some(7)
        );
        assert_eq!(
            decide_login(Some((7, Some(hash), false)), "wrong password"),
            None,
            "a wrong password against a real hash must still be rejected"
        );
    }

    #[test]
    fn decide_login_rejects_an_unknown_name_a_null_hash_and_a_disabled_principal() {
        // No row at all: unknown name (or `kind != 'user'`, excluded by
        // verify_login's own query).
        assert_eq!(decide_login(None, "anything"), None);
        // A `user` principal that exists but has never had a password set.
        assert_eq!(decide_login(Some((1, None, false)), "anything"), None);
        // A real hash, but the principal is disabled.
        let hash = hash_password("right password").unwrap();
        assert_eq!(
            decide_login(Some((1, Some(hash), true)), "right password"),
            None,
            "a disabled principal must be rejected even with the correct password"
        );
    }

    /// The timing-oracle fix's actual claim: every rejection path below
    /// calls `verify_password` (and therefore runs the same Argon2id work)
    /// exactly once, against either a real hash or `DUMMY_LOGIN_HASH`, so a
    /// caller cannot use "did this answer instantly or after Argon2id ran"
    /// to tell "no such user" apart from "wrong password for a real user".
    /// This cannot assert wall-clock timing reliably in CI, so instead it
    /// pins the thing that *makes* the timing uniform: `DUMMY_LOGIN_HASH`
    /// itself is a real, verifiable PHC string (not a shortcut like an
    /// empty string `verify_password` would reject without doing any KDF
    /// work at all — see `a_malformed_stored_hash_fails_closed_rather_than_panicking`
    /// above), so substituting it costs a real Argon2id call every time.
    #[test]
    fn the_dummy_login_hash_is_a_real_verifiable_argon2_hash_not_a_free_rejection() {
        assert!(
            PasswordHash::new(DUMMY_LOGIN_HASH).is_ok(),
            "DUMMY_LOGIN_HASH must be a well-formed PHC string, or verify_password's malformed-hash \
             fast path (see a_malformed_stored_hash_fails_closed_rather_than_panicking) would make \
             the miss path fast again, reopening the timing oracle this constant exists to close"
        );
        // Never actually matches anything real -- that would be a bizarre
        // coincidence with the arbitrary password below, not a contract.
        assert!(!verify_password(
            "whatever a caller happens to send",
            DUMMY_LOGIN_HASH
        ));
    }
}
