//! Admin session authentication: Argon2id passwords, session cookies, and
//! the middleware that gates `/admin/*` behind them.
//!
//! Deliberately a second, separate mechanism from `crate::snapshot::hash_key`
//! (SHA-256 over `api_keys`), not a generalisation of it. The two verbs being
//! secured are different in a way that changes which hash is correct:
//!
//! - An **API key** authenticates a *caller invoking a model*. It is
//!   generated by this process (`generate_key`, 32 bytes of OS randomness),
//!   so it is already maximally high-entropy — a fast hash (SHA-256) is
//!   correct because there is nothing an attacker with the hash could
//!   feasibly brute-force offline.
//! - A **password** authenticates a *human logging into the admin UI*. It is
//!   chosen by that human, so it is low-entropy by construction — the
//!   textbook case a slow, memory-hard KDF (Argon2id) exists for, to make
//!   offline brute-forcing a stolen `password_hash` expensive even against a
//!   weak password.
//!
//! A **session token** (the cookie value) sits with API keys, not passwords,
//! for the same entropy reason: it is generated here, not chosen by a human,
//! so `token_hash` in `migrations/0011_sessions.sql` is SHA-256 too.
use argon2::password_hash::{PasswordHash, PasswordHasher, PasswordVerifier, SaltString};
use argon2::Argon2;
use rand::RngCore;
use sha2::{Digest, Sha256};
use sqlx::PgPool;

/// The cookie name every login sets and every `/admin/*` request is checked
/// against.
pub const SESSION_COOKIE: &str = "fastllm_session";

/// How long a session is valid for after login. Short enough that a stolen
/// cookie has a bounded lifetime, long enough that an operator working
/// through the admin UI is not repeatedly kicked back to the login page.
pub const SESSION_TTL_HOURS: i64 = 12;

/// Hash a human-chosen password with Argon2id and OWASP's current default
/// parameters (`Argon2::default()`: 19 MiB memory, 2 iterations, 1-lane
/// parallelism), returning the full PHC string (`$argon2id$v=19$...`) that
/// `principals.password_hash` stores — self-describing, so a future
/// parameter change does not invalidate already-stored hashes.
pub fn hash_password(password: &str) -> anyhow::Result<String> {
    // Not `SaltString::generate`: that takes rand_core 0.6's `CryptoRngCore`,
    // a different major version of a different crate from this workspace's
    // own `rand` (0.9), and pulling it in as a real dependency just for this
    // one call is not worth it. 16 bytes of OS randomness from `rand`
    // (already a dependency for `control::api::generate_key`) encoded the
    // same way `generate` does internally is equivalent and adds nothing new
    // to the dependency tree.
    let mut salt_bytes = [0u8; 16];
    rand::rng().fill_bytes(&mut salt_bytes);
    let salt =
        SaltString::encode_b64(&salt_bytes).map_err(|e| anyhow::anyhow!("encoding salt: {e}"))?;
    let hash = Argon2::default()
        .hash_password(password.as_bytes(), &salt)
        .map_err(|e| anyhow::anyhow!("hashing password: {e}"))?;
    Ok(hash.to_string())
}

/// Verify a presented password against a stored PHC hash. `false` on any
/// mismatch *or* malformed stored hash — a corrupt `password_hash` must fail
/// closed, not panic or authenticate.
pub fn verify_password(password: &str, stored_hash: &str) -> bool {
    let Ok(parsed) = PasswordHash::new(stored_hash) else {
        return false;
    };
    Argon2::default()
        .verify_password(password.as_bytes(), &parsed)
        .is_ok()
}

/// 32 bytes of OS randomness, the same shape as `control::api::generate_key`
/// and for the same reason: this is what makes hashing it with SHA-256
/// (rather than Argon2id) the right call — see the module doc comment.
fn generate_session_token() -> String {
    let mut bytes = [0u8; 32];
    rand::rng().fill_bytes(&mut bytes);
    format!("sess-{}", hex::encode(bytes))
}

fn hash_session_token(token: &str) -> [u8; 32] {
    Sha256::digest(token.as_bytes()).into()
}

/// Create a session row for `principal_id` and return the plaintext token to
/// set as the cookie value. Like `create_key`, the plaintext is returned
/// exactly once and never stored — only its hash is.
pub async fn create_session(pool: &PgPool, principal_id: i64) -> Result<String, sqlx::Error> {
    let token = generate_session_token();
    let expires_at = chrono::Utc::now() + chrono::Duration::hours(SESSION_TTL_HOURS);
    sqlx::query("INSERT INTO sessions (token_hash, principal_id, expires_at) VALUES ($1, $2, $3)")
        .bind(hash_session_token(&token).to_vec())
        .bind(principal_id)
        .bind(expires_at)
        .execute(pool)
        .await?;
    Ok(token)
}

/// Resolve a presented cookie value to the principal it belongs to, or
/// `None` if it does not exist, has expired, or names a disabled principal.
/// Never a database error the caller has to plumb through — a lookup that
/// cannot resolve a session is the same "not authenticated" outcome
/// regardless of why.
pub async fn authenticate_session(pool: &PgPool, token: &str) -> Option<i64> {
    let row: Option<(i64,)> = sqlx::query_as(
        "SELECT s.principal_id FROM sessions s
         JOIN principals p ON p.id = s.principal_id
         WHERE s.token_hash = $1 AND s.expires_at > now() AND NOT p.disabled",
    )
    .bind(hash_session_token(token).to_vec())
    .fetch_optional(pool)
    .await
    .ok()?;
    row.map(|(id,)| id)
}

/// Invalidate a session (logout). Deleting a row nobody presents again is a
/// no-op, not an error — logging out twice, or with a cookie already
/// expired, must not surface as a failure to the browser.
pub async fn delete_session(pool: &PgPool, token: &str) -> Result<(), sqlx::Error> {
    sqlx::query("DELETE FROM sessions WHERE token_hash = $1")
        .bind(hash_session_token(token).to_vec())
        .execute(pool)
        .await?;
    Ok(())
}

/// Look up a principal by name and verify a presented password against its
/// `password_hash`. `None` covers every rejection reason (no such
/// principal, wrong `kind`, no password set, disabled, wrong password)
/// without distinguishing which — the same "don't tell an attacker which
/// part was wrong" reasoning any login form follows.
pub async fn verify_login(pool: &PgPool, name: &str, password: &str) -> Option<i64> {
    let row: Option<(i64, Option<String>, bool)> = sqlx::query_as(
        "SELECT id, password_hash, disabled FROM principals WHERE name = $1 AND kind = 'user'",
    )
    .bind(name)
    .fetch_optional(pool)
    .await
    .ok()?;
    let (id, hash, disabled) = row?;
    if disabled {
        return None;
    }
    let hash = hash?;
    if verify_password(password, &hash) {
        Some(id)
    } else {
        None
    }
}

/// Set (or replace) a principal's password, promoting it to `kind = 'user'`
/// if it was not already — the same "this is now a login-capable identity"
/// step `fastllm-proxy set-password` and `PUT /admin/principals/{id}/password`
/// both need. Hashed with Argon2id, never encrypted: unlike
/// `model_backends.upstream_api_key` (which the proxy must present to a
/// backend and so must be recoverable), nothing ever needs the plaintext
/// password back.
pub async fn set_password(pool: &PgPool, principal_id: i64, password: &str) -> anyhow::Result<()> {
    let hash = hash_password(password)?;
    sqlx::query("UPDATE principals SET kind = 'user', password_hash = $1 WHERE id = $2")
        .bind(hash)
        .bind(principal_id)
        .execute(pool)
        .await?;
    Ok(())
}

/// Bootstraps (or resets) the very first admin login: finds or creates a
/// `kind = 'user'` principal named `name`, sets its password, and grants it
/// the `admin` role if it did not already have some role — `fastllm-proxy
/// set-password` is the only caller, and its whole reason to exist is that a
/// freshly migrated database otherwise has a `password_hash` column nobody
/// can ever fill in through the (session-gated) admin API itself.
pub async fn bootstrap_admin_user(
    pool: &PgPool,
    name: &str,
    password: &str,
) -> anyhow::Result<i64> {
    let mut tx = pool.begin().await?;
    let existing: Option<i64> = sqlx::query_scalar("SELECT id FROM principals WHERE name = $1")
        .bind(name)
        .fetch_optional(&mut *tx)
        .await?;
    let principal_id = match existing {
        Some(id) => id,
        None => {
            sqlx::query_scalar(
                "INSERT INTO principals (kind, name) VALUES ('user', $1) RETURNING id",
            )
            .bind(name)
            .fetch_one(&mut *tx)
            .await?
        }
    };
    let hash = hash_password(password)?;
    sqlx::query("UPDATE principals SET kind = 'user', password_hash = $1 WHERE id = $2")
        .bind(hash)
        .bind(principal_id)
        .execute(&mut *tx)
        .await?;
    let has_any_role: bool =
        sqlx::query_scalar("SELECT EXISTS(SELECT 1 FROM principal_roles WHERE principal_id = $1)")
            .bind(principal_id)
            .fetch_one(&mut *tx)
            .await?;
    if !has_any_role {
        sqlx::query(
            "INSERT INTO principal_roles (principal_id, role_id)
             SELECT $1, id FROM roles WHERE name = 'admin'
             ON CONFLICT DO NOTHING",
        )
        .bind(principal_id)
        .execute(&mut *tx)
        .await?;
    }
    tx.commit().await?;
    Ok(principal_id)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_password_round_trips_through_hash_and_verify() {
        let hash = hash_password("correct horse battery staple").unwrap();
        assert!(verify_password("correct horse battery staple", &hash));
    }

    #[test]
    fn the_wrong_password_is_rejected() {
        let hash = hash_password("correct horse battery staple").unwrap();
        assert!(!verify_password("wrong password", &hash));
    }

    #[test]
    fn a_malformed_stored_hash_fails_closed_rather_than_panicking() {
        assert!(!verify_password("anything", "not-a-phc-string"));
        assert!(!verify_password("anything", ""));
    }

    #[test]
    fn two_hashes_of_the_same_password_differ_by_salt() {
        // Argon2id salts randomly per call; two hashes of the same
        // plaintext must not be byte-identical, or a stolen `password_hash`
        // column would leak which users share a password.
        let a = hash_password("same-password").unwrap();
        let b = hash_password("same-password").unwrap();
        assert_ne!(a, b);
        assert!(verify_password("same-password", &a));
        assert!(verify_password("same-password", &b));
    }
}
