//! The committed CRD against the types it was generated from.
//!
//! `operator/deploy/crd.yaml` is committed so installing the operator needs
//! nothing but `kubectl`. That convenience is also how a manifest goes stale:
//! a field added to `FastllmProxySpec` and not regenerated is a field the API
//! server rejects, at apply time, in someone else's cluster.
//!
//! Fix a failure by regenerating, never by editing the YAML:
//!
//!   cargo run -p fastllm-operator --bin crdgen > operator/deploy/crd.yaml

use kube::CustomResourceExt;

#[test]
fn the_committed_crd_matches_the_rust_types() {
    let committed =
        std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/deploy/crd.yaml"))
            .expect("operator/deploy/crd.yaml");

    let generated = format!(
        "# Generated by `cargo run -p fastllm-operator --bin crdgen`. Do not edit.\n{}",
        serde_yaml::to_string(&fastllm_operator::crd::FastllmProxy::crd()).unwrap()
    );

    assert_eq!(
        committed.trim_end(),
        generated.trim_end(),
        "operator/deploy/crd.yaml is stale — regenerate it with \
         `cargo run -p fastllm-operator --bin crdgen > operator/deploy/crd.yaml`"
    );
}
